// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcWZXr8ubtVhh5Ko9BqDTqwSvVWA6f2dE',
    appId: '1:871883074972:web:7f46b14f3ca210974a2c59',
    messagingSenderId: '871883074972',
    projectId: 'habit-tracker-f20a4',
    authDomain: 'habit-tracker-f20a4.firebaseapp.com',
    storageBucket: 'habit-tracker-f20a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0WvOKjXGQY8PLpjdvJi075XI-uGPuesk',
    appId: '1:871883074972:android:5ae9e23a3ee8aaa84a2c59',
    messagingSenderId: '871883074972',
    projectId: 'habit-tracker-f20a4',
    storageBucket: 'habit-tracker-f20a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEgQSmkatl0bqukyfKwHwp8qJYbpuaZaE',
    appId: '1:871883074972:ios:37494b341b7197a74a2c59',
    messagingSenderId: '871883074972',
    projectId: 'habit-tracker-f20a4',
    storageBucket: 'habit-tracker-f20a4.firebasestorage.app',
    iosBundleId: 'com.example.habitTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEgQSmkatl0bqukyfKwHwp8qJYbpuaZaE',
    appId: '1:871883074972:ios:37494b341b7197a74a2c59',
    messagingSenderId: '871883074972',
    projectId: 'habit-tracker-f20a4',
    storageBucket: 'habit-tracker-f20a4.firebasestorage.app',
    iosBundleId: 'com.example.habitTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcWZXr8ubtVhh5Ko9BqDTqwSvVWA6f2dE',
    appId: '1:871883074972:web:b507b888455a53134a2c59',
    messagingSenderId: '871883074972',
    projectId: 'habit-tracker-f20a4',
    authDomain: 'habit-tracker-f20a4.firebaseapp.com',
    storageBucket: 'habit-tracker-f20a4.firebasestorage.app',
  );
}
